# # Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
# name: Metrics
# on:
#   # Run daily at midnight
#   schedule: [{cron: "0 0 * * *"}]
#   # Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
#   # Currently only want to run every hour.. Don't know how much this would eat away at my 'free' compute time.
#   # push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     name: Generate GitHub Metrics 📊
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate metrics and update Gist
#         uses: lowlighter/metrics@v4
#         with:
#           token: ${{ secrets.GH_GIST_TOKEN }}
#           user: lovc21
#           template: classic
#           base: header,activity,community,repositories,metadata
#           config_timezone: Europe/Ljubljana
#           committer_message: "🔄 Update metrics for lovc21"
#           committer_gist: ${{ secrets.METRICS_GIST_ID }}
#           output_action: gist
#           plugin_followup: yes
#           plugin_followup_sections: repositories
#           plugin_gists: yes
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: half-year
#           plugin_lines: yes
#           plugin_people: yes
#           plugin_people_limit: 24
#           plugin_people_size: 28
#           plugin_people_types: followers,following
#           plugin_sponsors: yes
#           plugin_sponsors_sections: goal,about
#           plugin_traffic: yes
